-- PostgreSQL 版的 `messages` 資料表

-- 這行是為了確保資料表存在時先刪除它，方便重新建立。
-- 如果有messages這資料表就刪除原本的messages資料表
DROP TABLE IF EXISTS messages;

-- 建立 `messages` 資料表
CREATE TABLE messages (
    id SERIAL PRIMARY KEY, -- 使用 SERIAL 或 GENERATED BY DEFAULT AS IDENTITY 來實現自動遞增
    sender_id INTEGER NOT NULL,
    receiver_id INTEGER NOT NULL,
    type VARCHAR(50) NOT NULL,
    content TEXT NOT NULL,
    metadata JSONB DEFAULT NULL, -- 推薦使用 JSONB 類型來儲存 JSON 資料
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    read_at TIMESTAMP WITH TIME ZONE DEFAULT NULL
);

-- 為 `sender_id`, `receiver_id`, 和 `type` 建立索引以提升查詢效能
CREATE INDEX idx_sender ON messages (sender_id);
CREATE INDEX idx_receiver ON messages (receiver_id);
CREATE INDEX idx_type ON messages (type);